# Generated by Django 6.0.4 on 2026-04-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursecontent_description_coursecontent_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='track',
            name='thumbnail',
        ),
    ]
