# Generated by Django 6.0.4 on 2026-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_thumbnail_remove_course_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
    ]
