# Generated by Django 6.0.4 on 2026-04-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
        migrations.AddField(
            model_name='course',
            name='playlist_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='courses/thumbnails/'),
        ),
        migrations.AddField(
            model_name='track',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='tracks/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DRF', 'Draft'), ('PSH', 'Published'), ('HIDE', 'Hidden')], default='PSH', max_length=4),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('DRF', 'Draft'), ('PSH', 'Published'), ('HIDE', 'Hidden')], default='PSH', max_length=4),
        ),
    ]
