# Generated by Django 6.0.4 on 2026-04-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_trackenrollment_is_completed_trackenrollment_score_and_more'),
        ('courses', '0012_remove_course_tag_course_playlist_id_and_more'),
    ]

    operations = [
    ]
