# Generated by Django 6.0.4 on 2026-05-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_merge_20260425_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(default='', max_length=255),
        ),
    ]
