# Generated by Django 6.0.3 on 2026-05-22 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_result', models.TextField(max_length=4000)),
                ('percentage_result', models.DecimalField(decimal_places=2, max_digits=3)),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.track')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
