# Generated by Django 6.0.3 on 2026-05-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_interviewresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresults',
            name='track_id',
        ),
        migrations.AddField(
            model_name='interviewresults',
            name='track_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
