# Generated by Django 6.0.3 on 2026-05-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_interviewresults_track_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresults',
            name='interviewed_at',
            field=models.DateField(auto_now=True),
        ),
    ]
