# Generated by Django 6.0.3 on 2026-05-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified_user_otp_secret'),
        ('users', '0005_user_is_active_user_skill_level'),
    ]

    operations = [
    ]
